# Generated by Django 5.2.1 on 2026-05-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isOffer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
    ]
