# Generated by Django 5.2.1 on 2026-05-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_isoffer_remove_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isOffer',
            field=models.BooleanField(default=False),
        ),
    ]
